version: '3'

services:
  couch:
    container_name: futura_db
    image: couchdb:latest
    env_file: /app/.env.local
    volumes:
      - couch_data:/opt/couchdb/data
    ports:
      - 5984:5984
    restart: on-failure

  admin:
    build: /admin 
    container_name: futura_admin
    env_file: /admin/.env.local
    ports:
      - 3000:80
    depends_on:
      - client
    restart: on-failure
    command: nginx -g 'daemon off;'

  client:
    build: /app
    container_name: futura_client
    env_file: /app/.env.local
    ports:
      - 4000:4000
    restart: on-failure
    command: node server.js
volumes:
  couch_data: