services:
  couch:
    container_name: futura_db
    image: couchdb:latest
    env_file: ./app/.env.local
    volumes:
      - couch_data:/opt/couchdb/data
    ports:
      - 5984:5984
    restart: on-failure
  
  admin:
    build: ./admin 
    container_name: futura_admin
    env_file: ./admin/.env.local
    depends_on: 
      - client
    ports:
      - 3000:80
    restart: on-failure
    command: nginx -g 'daemon off;'

  client:
    build: ./app
    container_name: futura_client
    env_file: ./app/.env.local
    ports:
      - 4000:4000
    depends_on:
      - couch
    restart: on-failure
    command: node server.js

  server:
    env_file: ./server/.env.local
    container_name: hist-arts_server
    build: ./server
    depends_on:
      - couch
    restart: on-failure
    command: npm run server
volumes:
  couch_data: